# Generated by Django 3.0.5 on 2023-05-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanagementapp', '0005_auto_20230429_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='lectureupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture_tittle', models.TextField()),
                ('chapter_number', models.CharField(max_length=200)),
                ('notes', models.FileField(upload_to='notes')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsmanagementapp.Staff')),
            ],
        ),
    ]
