# Generated by Django 3.0.5 on 2023-05-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanagementapp', '0007_auto_20230511_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Notes',
            field=models.FileField(blank=True, upload_to='notes', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='subject',
            name='ppt',
            field=models.FileField(blank=True, upload_to='notes', verbose_name='Presentations'),
        ),
        migrations.AddField(
            model_name='subject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='notes', verbose_name='Video'),
        ),
    ]
